set( "sim/private/controls/clouds/first_res_3d", 3)
set( "sim/private/controls/clouds/last_res_3d", 5)
set( "sim/private/controls/clouds/plot_radius", 1.4)
set( "sim/private/controls/clouds/overdraw_control", 0.1)
set( "sim/private/controls/clouds/ambient_gain", 1.24)
set( "sim/private/controls/clouds/diffuse_gain", 0)
set( "sim/private/controls/clouds/light_curve_ratio", 100)
set( "sim/private/controls/clouds/light_curve_power", 100)
-- set( "sim/private/controls/clouds/shad_radius" , 1.0)
-- set( "sim/private/controls/clouds/shad_alpha_dry" , 0.5)
-- set( "sim/private/controls/clouds/shad_alpha_wet", 0)
set( "sim/private/controls/clouds/count_ratio/0",0.5)
set( "sim/private/controls/clouds/count_ratio/1",0.5)
set( "sim/private/controls/clouds/count_ratio/2",0.5)
set( "sim/private/controls/clouds/count_ratio/3",0.5)
set( "sim/private/controls/clouds/count_ratio/4",0.5)
set( "sim/private/controls/clouds/check_z_hdr", 0.00)
-- set( "sim/private/controls/dome/sun_gain_1_hdr", 0.7)
set( "sim/private/controls/skyc/mie_scattering_ocast", 120.000000)
-- set( "sim/private/controls/skyc/shadow_level_clean", 1.000000)
set( "sim/private/controls/skyc/shadow_level_ocast", 1.000000)
-- set( "sim/private/controls/hdr/white_point", 10.0)
-- set( "sim/private/controls/atmo/atmo_scale_raleigh", 19.0)
-- set( "sim/private/controls/atmo/inscatter_gain_raleigh", 0)
-- set( "sim/private/controls/skyc/tone_ratio_hialt", 1)
-- set( "sim/private/controls/skyc/tone_ratio_clean", 1)
-- set( "sim/private/controls/skyc/tone_ratio_mount", 1)
-- set( "sim/private/controls/clouds/cloud_shadow_lighten_ratio",  1.00)
-- set( "sim/private/controls/clouds/shad_radius", 0.6)
-- set( "sim/private/controls/shadow/adhoc/extra_far",  1.0 )
-- set( "sim/private/controls/shadow/bias_const",  0.0 )
-- set( "sim/private/controls/shadow/bias_slope",  1.0 )
-- set( "sim/private/controls/shadow/extra_near",  1.0 )
-- set( "sim/private/controls/shadow/overlap_ratio",  0.001000 )
